
spring:
  datasource:
    url: jdbc:postgresql://bmxyl43h9ta5p7a26zgh-postgresql.services.clever-cloud.com:50013/bmxyl43h9ta5p7a26zgh
    username:  ukfqvbqqlrvzqlpwmuqk
    password:  QhLU8lhLWNnAkpIPhMQaY7lfofvMJZ
jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  